src/Footeo/Footeo.Web/Areas/Admin/ViewModels/Matches/Input/CreateMatchInputModel.cs
namespace Footeo.Web.Areas.Admin.ViewModels.Matches.Input
{
    using System.ComponentModel.DataAnnotations;

    public class CreateMatchInputModel
    {
        [Required]
        public int HomeTeamId { get; set; }

        [Required]
        public int AwayTeamId { get; set; }

        [Required]
        public int FieldId { get; set; }

        [Required]
        public int FixtureId { get; set; }
    }
}

src/Footeo/Footeo.Web/Areas/Referee/ViewModels/Matches/Input/AddMatchInfoInputModel.cs
namespace Footeo.Web.Areas.Referee.ViewModels.Matches.Input
{
    using System.ComponentModel.DataAnnotations;

    public class AddMatchInfoInputModel
    {
        private const int MaxGoalsValue = 30;
        private const int MinGoalsValue = 0;

        [Required]
        [Range(MinGoalsValue, MaxGoalsValue)]
        public int HomeTeamGoals { get; set; }

        [Required]
        [Range(MinGoalsValue, MaxGoalsValue)]
        public int AwayTeamGoals { get; set; }
    }
}

src/Footeo/Footeo.Web/ViewModels/Matches/Output/AllMatchesViewModel.cs
namespace Footeo.Web.ViewModels.Matches.Output
{
    using System.Collections.Generic;

    public class AllMatchesViewModel
    {
        public IEnumerable<MatchDetailsViewModel> Matches { get; set; }
    }
}

src/Footeo/Footeo.Web/ViewModels/Matches/Output/AllTeamMatchesViewModel.cs
namespace Footeo.Web.ViewModels.Matches.Output
{
    using System.Collections.Generic;

    public class AllTeamMatchesViewModel
    {
        public IEnumerable<TeamMatchViewModel> HomeMatches { get; set; }
        public IEnumerable<TeamMatchViewModel> AwayMatches { get; set; }
    }
}

src/Footeo/Footeo.Web/ViewModels/Matches/Output/MatchDetailsViewModel.cs
namespace Footeo.Web.ViewModels.Matches.Output
{
    public class MatchDetailsViewModel
    {
        private const string None = "N/A";

        public int Id { get; set; }
        public string FieldName { get; set; }

        public string RefereeFullName { get; set; }
        public string ShowReferee => string.IsNullOrWhiteSpace(this.RefereeFullName) ? None : this.RefereeFullName;

        public string HomeTeamName { get; set; }
        public string AwayTeamName { get; set; }
        public string ShowRivals => $"{this.HomeTeamName} vs {AwayTeamName}";

        public int HomeTeamGoals { get; set; }
        public int AwayTeamGoals { get; set; }

        public string Result { get; set; }
        public string ShowResult => string.IsNullOrWhiteSpace(this.Result) ? None : $"{this.HomeTeamGoals} : {this.AwayTeamGoals}";
    }
}

src/Footeo/Footeo.Web/ViewModels/Matches/Output/MatchFixtureViewModel.cs
namespace Footeo.Web.ViewModels.Matches.Output
{
    public class MatchFixtureViewModel : TeamMatchViewModel
    {

    }
}

src/Footeo/Footeo.Web/ViewModels/Matches/Output/TeamMatchViewModel.cs
namespace Footeo.Web.ViewModels.Matches.Output
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class TeamMatchViewModel
    {
        public string FixtureName { get; set; }

        [DataType(DataType.Time)]
        public DateTime Date { get; set; }
        public string ShowDate => this.Date.ToShortDateString();

        public string HomeTeamName { get; set; }
        public string AwayTeamName { get; set; }
        public string ShowRivals => $"{this.HomeTeamName} vs {this.AwayTeamName}";

        public int HomeTeamGoals { get; set; }
        public int AwayTeamGoals { get; set; }
        public string ShowResult => $"{this.HomeTeamGoals} : {this.AwayTeamGoals}";
    }
}

src/Footeo/Footeo.Web/Areas/Admin/Controllers/MatchesController.cs
namespace Footeo.Web.Areas.Admin.Controllers
{
    using Footeo.Common;
    using Footeo.Services.Contracts;
    using Footeo.Web.Areas.Admin.Controllers.Base;
    using Footeo.Web.Areas.Admin.ViewModels.Matches.Input;
    using Footeo.Web.ViewModels;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using System.Linq;

    public class MatchesController : AdminBaseController
    {
        private readonly ITeamLeaguesService teamLeaguesService;
        private readonly IFixturesService fixturesService;
        private readonly IFieldsService fieldsService;
        private readonly IPlayersService usersService;
        private readonly IMatchesService matchesService;

        public MatchesController(ITeamLeaguesService teamLeaguesService, IFixturesService fixturesService,
            IFieldsService fieldsService, IPlayersService usersService, IMatchesService matchesService)
        {
            this.teamLeaguesService = teamLeaguesService;
            this.fixturesService = fixturesService;
            this.fieldsService = fieldsService;
            this.usersService = usersService;
            this.matchesService = matchesService;
        }

        public IActionResult Create(int id)
        {
            // TODO: find other way without ViewData

            this.ViewData[GlobalConstants.HomeTeamsViewDataName] = this.teamLeaguesService.LeagueTable<SelectListItem>(id).ToList();
            this.ViewData[GlobalConstants.AwayTeamsViewDataName] = this.teamLeaguesService.LeagueTable<SelectListItem>(id).ToList();
            this.ViewData[GlobalConstants.FieldsViewDataName] = this.fieldsService.AllFields<SelectListItem>().ToList();
            this.ViewData[GlobalConstants.FixturesViewDataName] = this.fixturesService.AllFixtures<SelectListItem>(id).ToList();

            return this.View();
        }

        [HttpPost]
        public IActionResult Create(CreateMatchInputModel model)
        {
            var fixtureLeague = this.fixturesService.GetLeagueForFixture(model.FixtureId);

            // TODO: find other way without ViewData

            this.ViewData[GlobalConstants.HomeTeamsViewDataName] = this.teamLeaguesService.LeagueTable<SelectListItem>(fixtureLeague.Id).ToList();
            this.ViewData[GlobalConstants.AwayTeamsViewDataName] = this.teamLeaguesService.LeagueTable<SelectListItem>(fixtureLeague.Id).ToList();
            this.ViewData[GlobalConstants.FieldsViewDataName] = this.fieldsService.AllFields<SelectListItem>().ToList();
            this.ViewData[GlobalConstants.FixturesViewDataName] = this.fixturesService.AllFixtures<SelectListItem>(fixtureLeague.Id).ToList();

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (model.HomeTeamId == model.AwayTeamId)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamVsTeamErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            this.matchesService.CreateMatch(model.HomeTeamId, model.AwayTeamId, model.FieldId, model.FixtureId);

            var routeValues = new { Id = model.FixtureId, Area = GlobalConstants.EmptyArea };

            return this.RedirectToAction(controllerName: GlobalConstants.FixturesControllerName,
                                         actionName: GlobalConstants.DetailsActionName,
                                         routeValues: routeValues);
        }
    }
}

src/Footeo/Footeo.Web/Areas/Referee/Controllers/MatchesController.cs
namespace Footeo.Web.Areas.Referee.Controllers
{
    using Footeo.Common;
    using Footeo.Models;
    using Footeo.Services.Contracts;
    using Footeo.Web.ViewModels;
    using Footeo.Web.Areas.Referee.Controllers.Base;
    using Footeo.Web.Areas.Referee.ViewModels.Matches.Input;

    using Microsoft.AspNetCore.Mvc;

    public class MatchesController : RefereeBaseController
    {
        private readonly IMatchesService matchesService;
        private readonly IRefereesService refereesService;
        private readonly IPlayersService playersService;

        public MatchesController(IMatchesService matchesService, IRefereesService refereesService,
            IPlayersService playersService)
        {
            this.matchesService = matchesService;
            this.refereesService = refereesService;
            this.playersService = playersService;
        }

        public IActionResult Add() => this.View();

        [HttpPost]
        public IActionResult Add(int id, AddMatchInfoInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var matchExists = this.matchesService.MatchExistsById(id);
            if (!matchExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.MatchDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var matchHasResult = this.matchesService.MatchHasResult(id);
            if (matchHasResult)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.MatchHasResultErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var match = this.matchesService.GetMatchById<Match>(id);

            this.refereesService.AddResultToMatch(match.Id, model.HomeTeamGoals, model.AwayTeamGoals);

            var fixtureId = match.Fixture.Id;

            var routeValues = new { Id = fixtureId };

            return this.RedirectToAction(controllerName: GlobalConstants.FixturesControllerName,
                                         actionName: GlobalConstants.DetailsActionName,
                                         routeValues: routeValues);

        }

        public IActionResult Attend(int id)
        {
            var matchExists = this.matchesService.MatchExistsById(id);
            if (!matchExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.MatchDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var matchHasAreferee = this.matchesService.MatchHasReferee(id);
            if (matchHasAreferee)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.MatchHasRefereeErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var user = this.User.Identity.Name;

            this.refereesService.AttendAMatch(user, id);

            var match = this.matchesService.GetMatchById<Match>(id);
            var fixtureId = match.Fixture.Id;

            var routeValues = new { Id = fixtureId };

            return this.RedirectToAction(controllerName: GlobalConstants.FixturesControllerName,
                                         actionName: GlobalConstants.DetailsActionName,
                                         routeValues: routeValues);
        }
    }
}

src/Footeo/Footeo.Web/Areas/Admin/Views/Matches/Create.cshtml
@model Footeo.Web.Areas.Admin.ViewModels.Matches.Input.CreateMatchInputModel

@{
    ViewData["Title"] = "Create Match";

    var homeTeams = this.ViewData[GlobalConstants.HomeTeamsViewDataName] as IEnumerable<SelectListItem>;
    var awayTeams = this.ViewData[GlobalConstants.AwayTeamsViewDataName] as IEnumerable<SelectListItem>;
    var fields = this.ViewData[GlobalConstants.FieldsViewDataName] as IEnumerable<SelectListItem>;
    var fixtures = this.ViewData[GlobalConstants.FixturesViewDataName] as IEnumerable<SelectListItem>;
}

<div style="width:50%" class="d-flex justify-content-center align-items-center container">
    <h2 class="text-center" style="color:#00a78e">@this.ViewData["Title"]</h2>
    <hr class="hr-2" />
    <form asp-area="Admin" asp-controller="Matches" asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <div style="color:#00a78e" class="text-center">
                <label asp-for="HomeTeamId" class="control-label">Home Team</label>
            </div>
            <select asp-for="HomeTeamId" asp-items="homeTeams" class="form-control">
                <option selected="selected" disabled="disabled">Choose Home Team</option>
            </select>
            <span asp-validation-for="HomeTeamId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <div style="color:#00a78e" class="text-center">
                <label asp-for="AwayTeamId" class="control-label">Away Team</label>
            </div>
            <select asp-for="AwayTeamId" asp-items="awayTeams" class="form-control">
                <option selected="selected" disabled="disabled">Choose Away Team</option>
            </select>
            <span asp-validation-for="AwayTeamId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <div style="color:#00a78e" class="text-center">
                <label asp-for="FieldId" class="control-label">Field</label>
            </div>
            <select asp-for="FieldId" asp-items="fields" class="form-control">
                <option selected="selected" disabled="disabled">Choose Field</option>
            </select>
            <span asp-validation-for="FieldId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <div style="color:#00a78e" class="text-center">
                <label asp-for="FixtureId" class="control-label">Fixture</label>
            </div>
            <select asp-for="FixtureId" asp-items="fixtures" class="form-control">
                <option selected="selected" disabled="disabled">Choose Fixture</option>
            </select>
            <span asp-validation-for="FixtureId" class="text-danger"></span>
        </div>

        <hr class="hr-2" />

        <div class="text-center">
            <div class="form-group">
                <input type="submit" value="Create"style="background-color:#00a78e" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>