src/Footeo/Footeo.Web/ViewModels/Trophies/Output/AllTrophiesViewModel.cs
namespace Footeo.Web.ViewModels.Trophies.Output
{
    using System.Collections.Generic;

    public class AllTrophiesViewModel
    {
        public IEnumerable<TrophyViewModel> Trophies { get; set; }
    }
}

src/Footeo/Footeo.Web/ViewModels/Trophies/Output/TrophyViewModel.cs
namespace Footeo.Web.ViewModels.Trophies.Output
{
    public class TrophyViewModel
    {
        private const string NameSuffix = "Cup";

        public string Name { get; set; }

        public string ShowName => $"{this.Name} {NameSuffix}";
    }
}

src/Footeo/Footeo.Web/Areas/Admin/Controllers/TrophiesController.cs
namespace Footeo.Web.Areas.Admin.Controllers
{
    using System.Linq;

    using Footeo.Common;
    using Footeo.Services.Contracts;
    using Footeo.Web.Areas.Admin.Controllers.Base;
    using Footeo.Web.Areas.Admin.ViewModels.Leagues.Output;
    using Footeo.Web.ViewModels;

    using Microsoft.AspNetCore.Mvc;

    public class TrophiesController : AdminBaseController
    {
        private readonly ILeaguesService leaguesService;
        private readonly ITrophiesService trophiesService;
        private readonly ITeamLeaguesService teamLeaguesService;

        public TrophiesController(ILeaguesService leaguesService, ITrophiesService trophiesService, ITeamLeaguesService teamLeaguesService)
        {
            this.leaguesService = leaguesService;
            this.trophiesService = trophiesService;
            this.teamLeaguesService = teamLeaguesService;
        }

        public IActionResult TrophiesForLeagues()
        {
            var leagues = this.leaguesService.AllCompletedLeagues<LeagueViewModel>().ToList();
            var leaguesViewModel = new AllLeaguesViewModel
            {
                Leagues = leagues
            };

            return this.View(leaguesViewModel);
        }

        public IActionResult GenerateWinner(int id)
        {
            var leagueExists = this.leaguesService.LeagueExistsById(id);
            if (!leagueExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.LeagueDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var hasTeamAlreadyCurrentTrophy = this.teamLeaguesService.HasTeamAlreadyCurrentTrophy(id);
            if (hasTeamAlreadyCurrentTrophy)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamTrophyErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            this.trophiesService.CreateTrophy(id);

            var routeValues = new { Area = GlobalConstants.EmptyArea };

            return this.RedirectToAction(controllerName: GlobalConstants.LeaguesControllerName,
                                         actionName: GlobalConstants.CompletedActionName,
                                         routeValues: routeValues);
        }
    }
}

src/Footeo/Footeo.Web/Areas/Admin/Views/Trophies/TrophiesForLeagues.cshtml
@using Footeo.Services.Contracts

@model Footeo.Web.Areas.Admin.ViewModels.Leagues.Output.AllLeaguesViewModel

@inject ITeamLeaguesService TeamLeaguesService
@{
    ViewData["Title"] = "Completed Leagues";
}

<div class="container">
    <h2 class="text-center" style="color:#00a78e">@this.ViewData["Title"]</h2>
    <hr class="hr-2" />
    <div class="row" style="color:#8d9293; font-size:30px">
        @foreach (var league in Model.Leagues)
        {
            <div style="color:#00a78e" class="col-lg-6">@league.Name</div>
            <div class="col-lg-6">
                @if (!this.TeamLeaguesService.HasTeamAlreadyCurrentTrophy(league.Id))
                {
                    <a style="background-color:#00a78e" class="btn btn-primary" asp-area="Admin" asp-controller="Trophies" asp-action="GenerateWinner" asp-route-id="@league.Id">Generate</a>
                }
                else
                {
                    <span>Winner has been genereted</span>
                }
            </div>
        }
    </div>
</div>