src/Footeo/Footeo.Web/Controllers/FieldsController.cs
namespace Footeo.Web.Controllers
{
    using Footeo.Common;
    using Footeo.Services.Contracts;
    using Footeo.Web.Controllers.Base;
    using Footeo.Web.ViewModels.Fields.Output;

    using Microsoft.AspNetCore.Mvc;

    using System.Linq;

    using X.PagedList;

    public class FieldsController : BaseController
    {
        private readonly IFieldsService fieldsService;

        public FieldsController(IFieldsService fieldsService)
        {
            this.fieldsService = fieldsService;
        }

        public IActionResult All(int? pageNumber)
        {
            var nextPage = pageNumber ?? GlobalConstants.NextPageValue;

            var fields = this.fieldsService.AllFields<FieldViewModel>().ToList();

            var pagedFields = fields.ToPagedList(nextPage, GlobalConstants.MaxElementsOnPage);

            var fieldViewModels = new AllFieldsViewModel
            {
                Fields = pagedFields
            };

            return View(fieldViewModels);
        }
    }
}

src/Footeo/Footeo.Web/Controllers/FixturesController.cs
namespace Footeo.Web.Controllers
{
    using System.Linq;

    using Footeo.Common;
    using Footeo.Services.Contracts;
    using Footeo.Web.Controllers.Base;
    using Footeo.Web.ViewModels;
    using Footeo.Web.ViewModels.Fixtures.Output;
    using Footeo.Web.ViewModels.Matches.Output;

    using Microsoft.AspNetCore.Mvc;

    public class FixturesController : BaseController
    {
        private readonly IFixturesService fixturesService;
        private readonly ILeaguesService leaguesService;
        private readonly IMatchesService matchesService;

        public FixturesController(IFixturesService fixturesService, ILeaguesService leaguesService, IMatchesService matchesService)
        {
            this.fixturesService = fixturesService;
            this.leaguesService = leaguesService;
            this.matchesService = matchesService;
        }

        public IActionResult All(int id)
        {
            var leagueExists = this.leaguesService.LeagueExistsById(id);
            if (!leagueExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.LeagueDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var fixtures = this.fixturesService.AllFixtures<FixtureViewModel>(id)
                                               .OrderBy(f => f.Name)
                                               .ToList();

            var fixturesViewModel = new AllFixturesViewModel
            {
                Fixtures = fixtures
            };

            return View(fixturesViewModel);
        }

        public IActionResult Details(int id)
        {
            var fixtureExists = this.fixturesService.FixtureExistsById(id);
            if (!fixtureExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.FixtureDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var matches = this.matchesService.MatchesByFixture<MatchDetailsViewModel>(id).ToList();
            var matchesViewModel = new AllMatchesViewModel
            {
                Matches = matches
            };

            return this.View(matchesViewModel);
        }
    }
}

src/Footeo/Footeo.Web/Controllers/LeaguesController.cs
namespace Footeo.Web.Controllers
{
    using Footeo.Services.Contracts;
    using Footeo.Web.Controllers.Base;
    using Footeo.Web.ViewModels.Leagues.Output;
    using Footeo.Web.ViewModels.TeamLeagues.Output;
    using Footeo.Web.ViewModels;
    using Footeo.Common;

    using System.Linq;

    using Microsoft.AspNetCore.Mvc;

    public class LeaguesController : BaseController
    {
        private readonly ILeaguesService leaguesService;
        private readonly ITeamLeaguesService teamLeaguesService;

        public LeaguesController(ILeaguesService leaguesService, ITeamLeaguesService teamLeaguesService)
        {
            this.leaguesService = leaguesService;
            this.teamLeaguesService = teamLeaguesService;
        }

        public IActionResult Pending()
        {
            var leagues = this.leaguesService.AllPendingLeagues<PendingLeagueViewModel>().ToList();

            var leagueViewModels = new AllPendingLeaguesViewModel
            {
                Leagues = leagues
            };

            return View(leagueViewModels);
        }

        public IActionResult InProgress()
        {
            var leagues = this.leaguesService.AllInProgressLeagues<InProgressLeagueViewModel>().ToList();

            var leagueViewModels = new AllInProgressLeaguesViewModel
            {
                Leagues = leagues
            };

            return View(leagueViewModels);
        }

        public IActionResult Completed()
        {
            var leagues = this.leaguesService.AllCompletedLeagues<CompletedLeagueViewModel>().ToList();

            var leagueViewModels = new AllCompletedLeaguesViewModel
            {
                Leagues = leagues
            };

            return View(leagueViewModels);
        }

        public IActionResult Table(int id)
        {
            var leagueExists = this.leaguesService.LeagueExistsById(id);
            if (!leagueExists)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.LeagueDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorViewModel);
            }

            var teams = this.teamLeaguesService.LeagueTable<TeamLeagueViewModel>(id)
                                               .OrderByDescending(p => p.Points)
                                               .ThenByDescending(gd => gd.GoalDifference)
                                               .ThenByDescending(gf => gf.GoalsFor)
                                               .ToList();

            var allPlayedMatches = this.teamLeaguesService.AllPlayedMatchesCount(id);
            if (allPlayedMatches == GlobalConstants.AllPlayedMatchesInLeague)
            {
                this.leaguesService.SetLeagueStatusToCompleted(id);
            }

            var leagueTableViewModel = new LeagueTableViewModel
            {
                Teams = teams
            };

            return this.View(leagueTableViewModel);
        }
    }
}

src/Footeo/Footeo.Web/Controllers/TeamsController.cs
namespace Footeo.Web.Controllers
{
    using Footeo.Common;
    using Footeo.Services.Contracts;
    using Footeo.Web.Controllers.Base;
    using Footeo.Web.ViewModels;
    using Footeo.Web.ViewModels.Teams.Output;
    using Footeo.Web.ViewModels.Players.Output;
    using Footeo.Web.ViewModels.Trophies.Output;
    using Footeo.Web.ViewModels.Matches.Output;

    using System.Linq;

    using Microsoft.AspNetCore.Mvc;

    using AutoMapper;

    using X.PagedList;

    public class TeamsController : BaseController
    {
        private readonly ITeamsService teamsService;
        private readonly IPlayersService playersService;
        private readonly IMapper mapper;

        public TeamsController(ITeamsService teamsService, IPlayersService playersService, IMapper mapper)
        {
            this.teamsService = teamsService;
            this.playersService = playersService;
            this.mapper = mapper;
        }

        public IActionResult All(int? pageNumber)
        {
            var nextPage = pageNumber ?? GlobalConstants.NextPageValue;

            var teams = this.teamsService.AllTeams<TeamViewModel>().OrderBy(t => t.Name).ToList();

            var pagedteams = teams.ToPagedList(nextPage, GlobalConstants.MaxElementsOnPage);

            var teamViewModels = new AllTeamsViewModel
            {
                Teams = pagedteams
            };

            return View(teamViewModels);
        }

        public IActionResult Players(int id)
        {
            var teamExists = this.teamsService.TeamExistsById(id);
            if (!teamExists)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorModel);
            }

            var players = this.playersService.PlayersByTeam<PlayerTeamViewModel>(id).ToList();

            var teamPlayersViewModel = new TeamPlayersViewModel
            {
                Players = players
            };

            return this.View(teamPlayersViewModel);
        }

        public IActionResult Trophies(int id)
        {
            var teamExists = this.teamsService.TeamExistsById(id);
            if (!teamExists)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorModel);
            }

            var trophies = this.teamsService.AllTrophiesByTeamId<TrophyViewModel>(id).ToList();

            var allTrophiesViewModel = new AllTrophiesViewModel
            {
                Trophies = trophies
            };

            return this.View(allTrophiesViewModel);
        }

        public IActionResult Matches(int id)
        {
            var teamExists = this.teamsService.TeamExistsById(id);
            if (!teamExists)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorModel);
            }

            var homeMatches = this.teamsService.AllHomeMatchesByTeamId(id).ToList();
            var awayMatches = this.teamsService.AllAwayMatchesByTeamId(id).ToList();

            var mappedHomeMatches = this.mapper.ProjectTo<TeamMatchViewModel>(homeMatches.AsQueryable());
            var mappedAwayMatches = this.mapper.ProjectTo<TeamMatchViewModel>(awayMatches.AsQueryable());

            var allMatchesViewModel = new AllTeamMatchesViewModel
            {
                HomeMatches = mappedHomeMatches,
                AwayMatches = mappedAwayMatches
            };

            return this.View(allMatchesViewModel);
        }

        public IActionResult Details(int id)
        {
            var teamExists = this.teamsService.TeamExistsById(id);
            if (!teamExists)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = ErrorMessages.TeamDoesNotExistsErrorMessage
                };

                return this.View(viewName: GlobalConstants.ErrorViewName, model: errorModel);
            }

            var teamDetailsViewModel = this.teamsService.GetTeamById<TeamDetailsViewModel>(id);

            return this.View(teamDetailsViewModel);
        }
    }
}

src/Footeo/Footeo.Web/Views/Shared/FaviconPartial.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

src/Footeo/Footeo.Web/Views/Shared/_AdminNavbarPartial.cshtml
<li>
    <a asp-area="Admin" asp-controller="Leagues" asp-action="Create">League</a>
</li>
<li>
    <a asp-area="Admin" asp-controller="Fixtures" asp-action="Create">Fixture</a>
</li>
<li>
    <a asp-area="" asp-controller="Leagues" asp-action="InProgress">Match</a>
</li>
<li>
    <a asp-area="Admin" asp-controller="Trophies" asp-action="TrophiesForLeagues">Generate Trophy</a>
</li>
<li>
    <a asp-area="Admin" asp-controller="Fields" asp-action="Add">Field</a>
</li>

src/Footeo/Footeo.Web/Views/Shared/_CaptainNavbarPartial.cshtml
<li>
    <a asp-controller="Leagues" asp-action="Pending" class="btn btn-dark">Join League</a>
</li>

src/Footeo/Footeo.Web/Views/Shared/_Layout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <partial name="FaviconPartial" />
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8" />
    <title>Footeo a Football Event Organizer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Forward Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <!-- js -->
    <script src="~/js/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- js -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
</head>
<body>
    <!-- header -->
    <div class="header">
        <div class="header-top">
            <!-- container -->
            <div class="container">
                <div class="header-top-left">
                    <partial name="_LoginPartial" />
                </div>
                <div class="clearfix"> </div>
            </div>
            <!-- //container -->
        </div>
        <div class="header-middle">
            <!-- container -->
            <div class="container">
                <div class="header-middle-logo">
                    <a asp-controller="Home" asp-action="Index">Footeo - Your Football Event Organizer</a>
                </div>
            </div>
            <!-- //container -->
        </div>
        <div class="top-nav">
            <!-- container -->
            <div class="container">
                <span class="menu">MENU</span>

                <ul class="nav1">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Leagues <span class="caret"></span></a>
                        <ul class="dropdown-menu" style="background-color:#1CD5B5" role="menu">
                            <li>
                                <a asp-controller="Leagues" asp-action="Pending">Pending</a>
                            </li>
                            <li>
                                <a asp-controller="Leagues" asp-action="InProgress">In Progress</a>
                            </li>
                            <li>
                                <a asp-controller="Leagues" asp-action="Completed">Completed</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a asp-controller="Teams" asp-action="All">Teams</a>
                    <li>
                    <li>
                        <a asp-controller="Referees" asp-action="All">Referees</a>
                    <li>
                    <li>
                        <a asp-controller="Fields" asp-action="All">Fields</a>
                    <li>
                </ul>
            </div>

            <!-- //container -->
        </div>
        <div class="blue"> </div>
    </div>
    @RenderBody()
    <hr class="hr-2" />
    <!-- footer -->
    <div class="footer">
        <!-- container -->
        <div class="container">
            <div class="footer-top">
                <div class="footer-grids">
                    <div class="col-md-3 f-address">
                        <h5>Address</h5>
                        <ul>
                            <li>Sofia, Bulgaria</li>
                            <li>kv. Lozenets</li>
                            <li>Telephone: +359 884 695 169</li>
                            <li>E-mail : <a href="mailto:adskidolen@gmail.com">adskidolen@gmail.com</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 f-address f-contact">
                        <h5>Stay in Touch</h5>
                        <form>
                            <input type="text" placeholder="Email address" required="">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                    <div class="col-md-3 footer-logo">
                        <a asp-controller="Home" asp-action="Index">Footeo</a>
                        <div class="footer-left">
                            <ul>
                                <li><a class="facebook" href="https://www.facebook.com/paunski777777"></a></li>
                                <li><a class="linked-in" href="https://www.linkedin.com/in/alexander-paunski-02189516b/"></a></li>
                                <li><a class="you-tube" href="https://www.youtube.com/"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="footer-bottom">
                    <div class="copyright">
                        <p>© @DateTime.UtcNow.Year - Footeo. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <!-- //container -->
    </div>
    <!-- //footer -->
    @section Scripts
        {
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                $(".scroll").click(function (event) {
                    event.preventDefault();
                    $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
                });
            });
        </script>
        <!-- start-smoth-scrolling -->

        <script type="text/javascript">
            $(document).ready(function () {
                /*
                var defaults = {
                        containerID: 'toTop', // fading element id
                    containerHoverID: 'toTopHover', // fading element hover id
                    scrollSpeed: 1200,
                    easingType: 'linear'
                    };
                */

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>

        <!-- script-for-menu -->
        <script>
            $("span.menu").click(function () {
                $("ul.nav1").slideToggle(300, function () {
                    // Animation complete.
                });
            });

        </script>
        <!-- /script-for-menu -->
    }
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
    <!-- content-Get-in-touch -->

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Footeo/Footeo.Web/Views/Shared/_PlayerInTeamPartial.cshtml
<li>
    <a asp-controller="Leagues" asp-action="Pending">Pending Leagues</a>
</li>

src/Footeo/Footeo.Web/Views/Shared/_PlayerNavbarPartial.cshtml
<li>
    <a asp-area="Player" asp-controller="Teams" asp-action="Create" class="btn btn-dark">Create Team</a>
</li>
<li>
    <a asp-controller="Teams" asp-action="All" class="btn btn-dark">Join Team</a>
</li>

src/Footeo/Footeo.Web/Views/Shared/_RefereeNavbarPartial.cshtml
<li>
    <a asp-controller="Leagues" asp-action="InProgress">Attend a Match</a>
</li>